module.exports =
  {
    doesntlike: ['linux'],
    likes: ['gnu/linux',
      'gnu / linux',
      'gnu+linux',
      'gnu + linux',
      'gnu plus linux',
      'gnu slash linux',
      'gnu&linux',
      'gnu & linux',
      'gnu and linux',
      'gnu n linux',
      'gnu n\' linux',
      'gnu \'n linux',
      'gnu \'n\' linux',
      'linux/gnu',
      'linux / gnu',
      'linux+gnu',
      'linux + gnu',
      'linux plus gnu',
      'linux slash gnu',
      'linux&gnu',
      'linux & gnu',
      'linux and gnu',
      'linux n gnu',
      'linux n\' gnu',
      'linux \'n gnu',
      'linux \'n\' gnu',
      'red hat linux',
      'mandrake linux',
      'suse linux',
      'aurora sparc linux',
      'berry linux',
      'edulinux',
      'engarde secure linux',
      'linpus linux',
      'ojuba linux',
      'sugar-on-a-stick linux',
      'yellow dog linux',
      'fermi linux',
      'miracle linux',
      'oracle linux',
      'red flag linux',
      'scientific linux',
      'mandriva linux',
      'pclinuxos',
      'unity linux',
      'caldera openlinux',
      'caos linux',
      'turbolinux',
      'vine linux',
      'kali linux',
      'linuxbbq',
      'astra linux',
      'corel linux',
      'crunchbang linux',
      'dreamlinux',
      'handylinux',
      'mx linux',
      'nepalinux',
      'skolelinux',
      'sparkylinux',
      'sunwah linux',
      'bodhi linux',
      'galsoft linux',
      'iskolinux',
      'impi linux',
      'kuki linux',
      'linux lite',
      'linux mint',
      'linuxmce',
      'linuxtle',
      'molinux',
      'poseidon linux',
      'damn small linux',
      'feather linux',
      'austrumi linux',
      'frugalware linux',
      'mulinux',
      'simplelinux',
      'topologilinux',
      'vectorlinux',
      'winlinux',
      'dnalinux',
      'calculate linux',
      'container linux',
      'funtoo linux',
      'sabayon linux',
      'tin hat linux',
      'arch linux',
      'chakra linux',
      'frugalware linux',
      'antergos linux',
      'manjaro linux',
      'alpine linux',
      'cayote linux',
      'devil-linux',
      'dslinux',
      'familiar linux',
      'foresight linux',
      'gobolinux',
      'lunar linux',
      'mcc interim linux',
      'mklinux',
      'mobilinux',
      'montavista linux',
      'ps2 linux',
      'prevas industrial linux',
      'puppy linux',
      'softlanding linux',
      'tinfoil hat linux',
      'tiny core linux',
      'void linux',
      'gentoo linux',
      'turnkey linux',
      'gentoo linux',
      'trisquel linux',
      'gentoo linux',
      'parabola linux',
      'dragora linux',
      'gentoo linux',
      'yggrasil linux',
      'yggrasil linux/x',
      'musix linux'],
    copypasta: [`I'd just like to interject for a moment.  What you're referring to as Linux,
is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux.
Linux is not an operating system unto itself, but rather another free component
of a fully functioning GNU system made useful by the GNU corelibs, shell
utilities and vital system components comprising a full OS as defined by POSIX.

Many computer users run a modified version of the GNU system every day,
without realizing it.  Through a peculiar turn of events, the version of GNU
which is widely used today is often called "Linux", and many of its users are
not aware that it is basically the GNU system, developed by the GNU Project.

There really is a Linux, and these people are using it, but it is just a
part of the system they use.  Linux is the kernel: the program in the system
that allocates the machine's resources to the other programs that you run.
The kernel is an essential part of an operating system, but useless by itself;
it can only function in the context of a complete operating system.  Linux is
normally used in combination with the GNU operating system: the whole system
is basically GNU with Linux added, or GNU/Linux.  All the so-called "Linux"
distributions are really distributions of GNU/Linux.
	`]
  }
